### PR TITLE
Get test running and passing as github actions on pull requests

### LINKED ISSUE #11: Automatically run tests in gitlab actions CI/CD
We ought to get tests running as a safety net to ensure that pull requests we accepts don't cause weird regressions.

There are already tests included in the repo, but running them locally failed

We should get them working and then make them in gitlab actions on merge requests as a gate before merging.

### PR DESCRIPTION
**Pull request by iokiwi**
## Why? 🤔

Sustainability, stability and quality assurance of this project (Relates to the following issue https://github.com/tgenv/tgenv/issues/11)

## What? :hammer_and_wrench:

Based on tfenv tests and github actions, this change runs tests as github actions on pull requests.

To get the tests to work I have opted to use more recent versions of terragrunt as the old ones were failing for reasons I don't think are relevant or specific to tgenv.

## Additional Links 🌐

Closes #11

### CODE REVIEW

**Comment by weyderfs** [comment]
@iokiwi, I have a suggestion you're using `ubuntu` and `macos` to run the tests. Maybe would be interesting include a `alpine` or some `RHEL` distro, what your opinion about this?

**Comment by iokiwi** [comment]
Thats not a bad Idea. I think it would be best to add additional test targets in a seperate PR though as
 * The scope of this PR is already quite big
 * Gitlab managed runners don't target those OS's so adding RHEL and alpine targets will require introducing docker image runtimes
 * That will require going beyond the gitlab runner `matrix` strategy
 * will require logic to install dependencies (curl, git etc) for the different OS's using the different package managers

My recommendation is to mere this PR and add your request as a new enhancement.

**Comment by iokiwi** [comment]
I think this one is good to go?

Asside from the suggestion to include alpine and RHEL as runtime targets which as discussed I believe should be in a seperate PR, is there any other feedback preventing approval of this PR?

File: test/test_list.sh [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+# set -uo pipefail;
```
Comment (Fabianoshz) [inline test/test_list.sh:3]: I see you commented this, but the `-o pipefail` is actually useful to catch code errors. The `-u` is not actually very useful because we have empty variables. `-o pipefail` could actually be used in every test I believe.

Also, instead of comment code if we don't want we should just remove.

File: test/test_list.sh [hunk 2]
```diff
@@ -1,5 +1,7 @@
...
+
 declare -a errors
 
 function error_and_proceed() {
```
Comment (Fabianoshz) [inline test/test_list.sh:7]: I think we can move this function to `helpers` instead of repeating it on every test file.

File: test/test_list.sh [hunk 3]
```diff
@@ -12,27 +14,36 @@ function error_and_die() {
   exit 1
 }
```
Comment (Fabianoshz) [inline test/test_list.sh:15]: Same as above

File: .github/workflows/test.yaml [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+    steps:
+      - uses: 'actions/checkout@v2'
+        with:
+          fetch-depth: 1
+      - name: 'Install Dependencies'
+        run: './test/install_deps.sh'
+      - name: 'Run all tests'
+        run: './test/run.sh'
+        shell: 'bash'
+      # - uses: 'docker/setup-buildx-action@v2'
```
Comment (Fabianoshz) [inline .github/workflows/test.yaml:32]: Do we need this comment? If we don't need let's just remove it.

**Review by Fabianoshz — CHANGES_REQUESTED** [review]
Hi @iokiwi, sorry for my delayed response, @weyderfs asked me to review but I was working on a lot of things.

Some nitpicks about commented code and aside from the `-o pipefail` only slight improvement suggestions from my part. I will answer faster from now on.

Edit: congrats BTW, it's nice to have tests.

File: test/test_list.sh (hunk 1 above)
Comment (iokiwi) [reply test/test_list.sh]: Ack - sorry I am normally better at going back and cleaning this up. I've uncommented pipefail and deleted other commented code.

File: .github/workflows/test.yaml (hunk 4 above)
Comment (iokiwi) [reply .github/workflows/test.yaml]: Ack. Done

File: test/test_list.sh (hunk 3 above)
Comment (iokiwi) [reply test/test_list.sh]: Fixed

**Review by Fabianoshz — APPROVED** [review]
LGTM

**Comment by iokiwi** [comment]
Lol I just learned the hard way why I need to use set -o pipefail and came back to reference your comment @Fabianoshz.
I just thought it might amuse you that I just now fully realized the value of your advice and wanted to thank you :)

**Comment by Fabianoshz** [comment]
Hey, glad I could help! :smiley:
